// <auto-generated />
namespace Fallout4Checklist.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CharacterArea : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CharacterArea));
        
        string IMigrationMetadata.Id
        {
            get { return "201601311924251_CharacterArea"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
